
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Table table1;
	private global::Gtk.CheckButton cbFri;
	private global::Gtk.CheckButton cbMon;
	private global::Gtk.CheckButton cbSat;
	private global::Gtk.CheckButton cbSun;
	private global::Gtk.CheckButton cbThu;
	private global::Gtk.CheckButton cbTue;
	private global::Gtk.CheckButton cbWed;
	private global::Gtk.Button btnSearch;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(7)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.cbFri = new global::Gtk.CheckButton ();
		this.cbFri.CanFocus = true;
		this.cbFri.Name = "cbFri";
		this.cbFri.Label = global::Mono.Unix.Catalog.GetString ("F");
		this.cbFri.DrawIndicator = true;
		this.cbFri.UseUnderline = true;
		this.table1.Add (this.cbFri);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbFri]));
		w1.LeftAttach = ((uint)(4));
		w1.RightAttach = ((uint)(5));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbMon = new global::Gtk.CheckButton ();
		this.cbMon.Name = "cbMon";
		this.cbMon.Label = global::Mono.Unix.Catalog.GetString ("M");
		this.cbMon.DrawIndicator = true;
		this.cbMon.UseUnderline = true;
		this.table1.Add (this.cbMon);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbMon]));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbSat = new global::Gtk.CheckButton ();
		this.cbSat.CanFocus = true;
		this.cbSat.Name = "cbSat";
		this.cbSat.Label = global::Mono.Unix.Catalog.GetString ("S");
		this.cbSat.DrawIndicator = true;
		this.cbSat.UseUnderline = true;
		this.table1.Add (this.cbSat);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbSat]));
		w3.LeftAttach = ((uint)(5));
		w3.RightAttach = ((uint)(6));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbSun = new global::Gtk.CheckButton ();
		this.cbSun.CanFocus = true;
		this.cbSun.Name = "cbSun";
		this.cbSun.Label = global::Mono.Unix.Catalog.GetString ("S");
		this.cbSun.DrawIndicator = true;
		this.cbSun.UseUnderline = true;
		this.table1.Add (this.cbSun);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbSun]));
		w4.LeftAttach = ((uint)(6));
		w4.RightAttach = ((uint)(7));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbThu = new global::Gtk.CheckButton ();
		this.cbThu.CanFocus = true;
		this.cbThu.Name = "cbThu";
		this.cbThu.Label = global::Mono.Unix.Catalog.GetString ("T");
		this.cbThu.DrawIndicator = true;
		this.cbThu.UseUnderline = true;
		this.table1.Add (this.cbThu);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbThu]));
		w5.LeftAttach = ((uint)(3));
		w5.RightAttach = ((uint)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbTue = new global::Gtk.CheckButton ();
		this.cbTue.CanFocus = true;
		this.cbTue.Name = "cbTue";
		this.cbTue.Label = global::Mono.Unix.Catalog.GetString ("T");
		this.cbTue.DrawIndicator = true;
		this.cbTue.UseUnderline = true;
		this.table1.Add (this.cbTue);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbTue]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbWed = new global::Gtk.CheckButton ();
		this.cbWed.CanFocus = true;
		this.cbWed.Name = "cbWed";
		this.cbWed.Label = global::Mono.Unix.Catalog.GetString ("W");
		this.cbWed.DrawIndicator = true;
		this.cbWed.UseUnderline = true;
		this.table1.Add (this.cbWed);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbWed]));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add (this.table1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.table1]));
		w8.X = 25;
		w8.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSearch = new global::Gtk.Button ();
		this.btnSearch.CanFocus = true;
		this.btnSearch.Name = "btnSearch";
		this.btnSearch.UseUnderline = true;
		this.btnSearch.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.fixed1.Add (this.btnSearch);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSearch]));
		w9.X = 247;
		w9.Y = 103;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w11.X = 77;
		w11.Y = 126;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnSearch.Clicked += new global::System.EventHandler (this.OnBtnSearchClicked);
	}
}
